// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button-wrap': string;
  'buttonWrap': string;
  'container': string;
  'header-wrap': string;
  'headerWrap': string;
  'user-wrap': string;
  'userWrap': string;
  'visible': string;
}
export const cssExports: CssExports;
export default cssExports;
